brew "direnv"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "ollama", restart_service: true
brew "ripgrep"
brew "stow"
brew "zoxide"

cask "brave-browser"
cask "chatgpt-atlas"
cask "codex"
cask "codex-app"
cask "discord"
cask "docker-desktop"
cask "font-blex-mono-nerd-font"
cask "google-chrome"
cask "microsoft-teams"
cask "obsidian"
cask "powershell"
cask "scroll-reverser"
cask "typeless"
cask "unity-hub"
cask "visual-studio-code"
cask "zed"
cask "zoom"
